default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%=  ENV["database_username"] %>
  password: <%=  ENV["database_password"] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: <%= ENV["dev_database_name"] %>

test:
  <<: *default
  database: <%= ENV["test_database_name"] %>

production:
  <<: *default
  database: db/production.sqlite3
